title: Delete this shit
url: "http://nickmauro.net"
baseurl: "/home"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "http://nickmauro.net"
footer_text: "One thought after the other"

sass:
    style: compressed
    sass_dir: _sass
